###Sign up request
POST http://localhost:5000/signup
Content-Type: application/x-www-form-urlencoded

name=mohan-test&email=mohantest@gmail.com&password=password-1&type=admin

###Login request
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mohantest@gmail.com",
    "password": "password-1"
}

### Access test auth route with JWT
GET http://localhost:5000/protected HTTP/1.1
Content-Type: application/json
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTM4N2NlOTg5ZTRiZTFlMmM5YjEiLCJpYXQiOjE2Mzc2Nzg1OTQsImV4cCI6MTYzNzc2NDk5NH0.z5EP39FEiEpQt4rcndYoXleTpsmALj9UlRlxBxehS5o